## the planner configurations; each config must have a type, which specifies
## the planner to be used; other parameters can be specified as well, depending 
## on the planner


right_arm:
  planner_configs:
    - PRMkConfigDefault
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
  projection_evaluator: joints(r_shoulder_pan_joint,r_shoulder_lift_joint)
  longest_valid_segment_fraction: 0.05

right_arm_and_torso:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
  projection_evaluator: joints(r_shoulder_pan_joint,r_shoulder_lift_joint)
  longest_valid_segment_fraction: 0.05

left_arm: 
  planner_configs:
    - SBLkConfigDefault 
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
  projection_evaluator: joints(l_shoulder_pan_joint,l_shoulder_lift_joint)
  longest_valid_segment_fraction: 0.05

left_arm_and_torso: 
  planner_configs:
    - SBLkConfigDefault 
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
  projection_evaluator: joints(l_shoulder_pan_joint,l_shoulder_lift_joint)
  longest_valid_segment_fraction: 0.05

arms:
  planner_configs:
    - SBLkConfigDefault 
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
  longest_valid_segment_fraction: 0.05
  projection_evaluator: joints(r_shoulder_pan_joint,l_shoulder_pan_joint)


planner_configs:

  PRMkConfigDefault:
    type: geometric::PRM

  SBLkConfigDefault:
    type: geometric::SBL

  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE

  RRTkConfigDefault:
    type: geometric::RRT

  RRTConnectkConfigDefault:
    type: geometric::RRTConnect

  LazyRRTkConfigDefault:
    type: geometric::LazyRRT

  ESTkConfigDefault:
    type: geometric::EST

  KPIECEkConfigDefault:
    type: geometric::KPIECE

  RRTStarkConfigDefault:
    type: geometric::RRTstar

  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
