controller_manager_ns: pr2_controller_manager
controller_list:
  - name: r_arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
  - name: l_arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
  - name: torso_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - torso_lift_joint
