locations:

  - name: above_table_01
    pose: 0.76 -0.2 0.88 0.1 -0.02 0.02
  - name: above_table_02
    pose: 0.63 0.05 0.91 -1.34 0.24 -0.24
  - name: above_table_03
    pose: 0.69 -0.02 0.845 1.0 -0.26 0.32
  - name: above_table_04
    pose: 0.6 -0.22 0.964 1.57 1.57 0.01
  - name: above_table_05
    pose: 0.716 -0.08 0.892 -2.30 0 1.2
  - name: below_table_01
    pose: 0.5 -0.3 0.45 0 0.35 -0.1
  - name: below_table_02
    pose: 0.55 -0.03 0.53 1.6 0.76 -0.08
  - name: below_table_03
    pose: 0.5 -0.35 0.45 1.6 0.9 -0.01
  - name: below_table_04
    pose: 0.57 -0.28 0.47 0.0 0.0 1.57
  - name: below_table_05
    pose: 0.55 -0.15 0.45 0 -0.45 -0.12

