locations:

  - name: right_shelf_01
    pose: 0.64 -0.32 1.380 0.0 -0.0 0.1
  - name: left_shelf_01
    pose: 0.52 0.14 1.440 1.0 0.05 0.0
  - name: sink_01
    pose: 0.54 -0.06 0.81 1.0 0.05 0.11
  - name: right_counter_01
    pose: 0.56 -0.56 0.94 0.0 -0.3 -0.1
  - name: sink_02
    pose: 0.7 -0.06 0.8 0.0 1.57 0.0
  - name: left_shelf_02
    pose: 0.52 0.155 1.420 1.0 0.05 0.90
  - name: right_counter_02
    pose: 0.69 -0.46 0.94 0.0 0.3 0.9
  - name: right_counter_03
    pose: 0.61 -0.57 0.95 -0.2 -0.1 0.0 #0.61 -0.57 0.95 0.3 -0.4 0.1
  - name: dishwasher_01
    pose: 0.21 -0.65 0.48 0.3 1.57 0.0
  - name: dishwasher_02
    pose: 0.01 -0.7 0.45 1.0 1.57 0.0
  - name: dishwasher_03
    pose: 0.43 -0.56 0.52 0.5 0.30 0.0  #0.46 -0.56 0.52 0.5 0.30 0.0
  - name: right_shelf_02
    pose: 0.605 -0.48 1.370 0.8 -0.0 0.3
  - name: right_counter_04
    pose: 0.66 -0.58 0.96 1.0 -0.6 -0.92



