# for now expects either "arms" or "right_arm"
group_name: right_arm

benchmark_service: /benchmark_planning_problem
world_frame: map
robot_model_root_frame: odom
spine_frame: torso_lift_link
experiment_group_name: tabletop

# of calls to the planner per experiment
average_count: 1

# list the planner_interfaces you want to benchmark with
# the benchmark server includes the ompl by default
planner_interfaces: 
  SBPLPlanner
#  SBLkConfigDefault

goal_tolerance:
  xyz: 0.02 0.02 0.02
  rpy: 0.05 0.05 0.05

# true: use the last waypoint in the previous experiment's trajectory as the start state for the next experiment 
# false: use the start state specified in the experiment description as the start state of that experiment
use_current_pose_as_start_state: true

apply_offset_to_collision_objects: false

#collision_object_offset:
#  xyz: -1.28 -0.9 0
#  rpy: 0 0.0 0

# only used for both_arms experiments
# this is currently needed to be on the param server for the single arm experiments as well :)
# pose of {r,l}_wrist_roll_links in the object frame
object_pose_in_gripper:
  right:
    xyz: -0.20 -0.1 0.0
    rpy: 0.0 0.0 0.0
  left:
    xyz: -0.20 0.1 0.0
    rpy: 0.0 0.0 0.0

initial_start_state:
  right: -1.5 0.017997624551430391 -0.005238188295824564 -1.4 -0.00041708680445573521 -0.74471175505726084 -0.0010002085575777642
  #right: -0.200890 1.192362 0.000000 -0.975790 -2.527019 -0.164829 2.498734
  left: 2.135, 0.803, 1.732, -1.905, 2.369, -1.680, 1.398
  #left: 1.5 1.0 0.005683010665493704 -1.4 0.00079943310185193195 -0.7439117804053561 0.00049889278955195238
  base: 0 0 0 
  spine: 0.1


